### ISSUE TITLE
Strange output umonting folder

### ISSUE THREAD

**Issue by alewaste** [bobafetthotmail/folder2ram#13] opened 2018-10-24 19:32 UTC
Hi,
I tried to unmount all folder and I get this output:

will now stop all mountpoints                                                       
stop /var/cache                                                                     
stop /var/log                                                                       
stop /var/tmp                                                                       
stop /var/lib/openmediavault/rrd                                                    
stop /var/spool                                                                     
skipping non-regular file "postfix/dev/log"                                         
skipping non-regular file "postfix/dev/random"                                      
skipping non-regular file "postfix/dev/urandom"                                     
skipping non-regular file "postfix/private/anvil"                                   
skipping non-regular file "postfix/private/bounce"                                  
skipping non-regular file "postfix/private/bsmtp"                                   
skipping non-regular file "postfix/private/defer"                                   
skipping non-regular file "postfix/private/discard"                                 
skipping non-regular file "postfix/private/error"                                   
skipping non-regular file "postfix/private/ifmail"                                  
skipping non-regular file "postfix/private/lmtp"                                    
skipping non-regular file "postfix/private/local"                                   
skipping non-regular file "postfix/private/maildrop"                                
skipping non-regular file "postfix/private/mailman"                                 
skipping non-regular file "postfix/private/omvnotificationfilter"                   
skipping non-regular file "postfix/private/proxymap"                                
skipping non-regular file "postfix/private/proxywrite"                              
skipping non-regular file "postfix/private/relay"                                   
skipping non-regular file "postfix/private/retry"                                   
skipping non-regular file "postfix/private/rewrite"                                 
skipping non-regular file "postfix/private/scache"                                  
skipping non-regular file "postfix/private/scalemail-backend"                       
skipping non-regular file "postfix/private/smtp"                                    
skipping non-regular file "postfix/private/tlsmgr"                                  
skipping non-regular file "postfix/private/trace"                                   
skipping non-regular file "postfix/private/uucp"                                    
skipping non-regular file "postfix/private/verify"                                  
skipping non-regular file "postfix/private/virtual"                                 
skipping non-regular file "postfix/public/cleanup"                                  
skipping non-regular file "postfix/public/flush"                                    
skipping non-regular file "postfix/public/pickup"                                   
skipping non-regular file "postfix/public/qmgr"                                     
skipping non-regular file "postfix/public/showq"                                    
stop /var/lib/rrdcached                                                             
stop /var/lib/monit                                                                 
stop /var/lib/php                                                                   
stop /var/lib/netatalk/CNID                                                        
stop /var/lib/mysql                                                                 
stop /root/viewpower/log                                                            
stop /root/viewpower/tomcat/logs                                                    
stop /root/viewpower/datas/log                                                      
stop /root/viewpower/config                                                         
stop /var/lib/smartmontools                                                         
stop /tmp                                                                           
stop /var/lib/dhcp

I didn't get "skipping file" before and I noticed some problem with warning email of OMV.
What's the meaning of this alert?

**Comment by bobafetthotmail** [comment] 2018-10-27 09:03
Hm, that's output from rsync, it says it isn't copying over the mentioned files as they are symlinks (links to a file). By default it does not copy them unless you use the **-l** argument.

but I call rsync with that argument too, as I do want it to copy everything over.

` rsync -o -g -A -X -q -r -l -t `

I'll see if I can reproduce the issue, as I have postfix installed here too even if I'm not using OMV.

**Comment by bobafetthotmail** [comment] 2018-10-27 09:39
Ok, uploaded it. You can download and install it following the instructions in the readme, and overwrite the current one. Eventually OMV will ship it as an updated package.

**Comment by alewaste** [comment] 2018-10-27 23:45
I installed the new script. Errors during unmounting are disappeared.
I checked the affected files and they are present... anyway I don't know how to reinstall postfix, because it's automatically installed by OMV.

Thank You.

**Comment by bobafetthotmail** [comment] 2018-10-28 05:36
If the files are present, there is no need to reinstall postfix. 

What I say below is for information purpose only.

OMV is based on Debian, so if you have ssh access you can reinstall postfix with (run this command as root or with "sudo")

**apt-get install --reinstall postfix**

Since you confirm that the updated script fixes the problem, I'm closing the issue.

**Closed by bobafetthotmail** 2018-10-28 05:36 UTC
